arm64: Fix CONFIG_64BIT leak to userspace
Commit c7c0eec disabled the use of config
options in uapi headers. Use __aarch64__ which is a compiler-defined
method of obtaining the architecture instead of CONFIG_64BIT.

Fixes the following error:
    error: kernel/google/raviole/arch/arm64/include/uapi/asm/sigcontext.h:
        leak CONFIG_64BIT to user-space

Change-Id: I90d24488ed844c1d540db711a6a52d4d9a016e51
Signed-off-by: v4lkyr <valkyr23@gmail.com>